import Head from "next/head";
import { DefaultLayout } from "@/layouts";
import { CurrentEpoch } from "@/components";
import { getCurrentEpoch } from "@/helpers";

interface HomeProps {
  currentEpoch: number;
}

export default function Home({ currentEpoch }: HomeProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://storage.edcilo.com/favicon.ico" />
      </Head>
      <DefaultLayout>
        <CurrentEpoch epoch={currentEpoch} />
      </DefaultLayout>
    </>
  );
}

export async function getServerSideProps() {
  const currentEpoch = getCurrentEpoch();
  return {
    props: {
      currentEpoch,
    },
  };
}
